package transport

// Golden vectors for SigV4, so the STATION's signer can be checked against this
// one without either running the other.
//
// THE PROBLEM THIS SOLVES. `station/bash/transports/objstore.sh` has to sign
// requests in bash, with openssl, on a machine nobody can log into. A signature
// that is wrong by one byte gets a 403 that names nothing - AWS deliberately
// does not say which part disagreed, because saying so would be an oracle - so
// "the credential is wrong", "the clock is wrong", "the canonical form is
// wrong" and "the region is wrong" all present identically.
//
// EVERY STAGE IS PINNED, not just the header. A port that gets one thing wrong
// should be told which thing: the canonical request, its hash, the string to
// sign, the four derived keys, and finally the signature. "403 Forbidden" is
// not a debuggable statement about six chained HMACs.
//
// Regenerate with:
//
//	go test ./internal/transport/ -run TestSigV4GoldenVectors -update-sigv4
//
// A diff in the committed file is a change to how this repository signs, and
// every station in the field signs the old way until it is re-planted.

import (
	"bytes"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"net/http"
	"net/url"
	"os"
	"strings"
	"testing"
	"time"
)

var updateSigV4 = flag.Bool("update-sigv4", false, "rewrite the committed SigV4 vector file")

const sigV4VectorPath = "../../tests/fixtures/sigv4-vectors.json"

type sigV4Case struct {
	Name   string            `json:"name"`
	Why    string            `json:"why"`
	Method string            `json:"method"`
	URL    string            `json:"url"`
	Body   string            `json:"body"`
	Header map[string]string `json:"header"`

	// Every stage, so a mismatch says where.
	CanonicalRequest string   `json:"canonicalRequest"`
	CanonicalHash    string   `json:"canonicalRequestSha256"`
	StringToSign     string   `json:"stringToSign"`
	SigningKeyChain  []string `json:"signingKeyChainHex"`
	Signature        string   `json:"signature"`
	Authorization    string   `json:"authorization"`
	AmzDate          string   `json:"amzDate"`
	PayloadHash      string   `json:"payloadSha256"`
}

type sigV4File struct {
	Note      string      `json:"note"`
	AccessKey string      `json:"accessKey"`
	SecretKey string      `json:"secretKey"`
	Region    string      `json:"region"`
	Service   string      `json:"service"`
	Now       string      `json:"now"`
	Cases     []sigV4Case `json:"cases"`
}

func TestSigV4GoldenVectors(t *testing.T) {
	// A published test credential. AKIDEXAMPLE is the one AWS uses in its own
	// SigV4 documentation and test suite, so these vectors can be checked
	// against somebody else's as well as against ours.
	c := creds{
		accessKey: "AKIDEXAMPLE",
		secretKey: "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY",
		region:    "eu-west-2",
		service:   "s3",
	}
	// Fixed, because a signature covers the clock. Real ones use time.Now.
	now := time.Date(2026, 9, 12, 13, 45, 30, 0, time.UTC)

	specs := []struct {
		name, why, method, rawURL, body string
		header                          map[string]string
	}{
		{
			name: "get-status", why: "the ordinary read: no body, no query",
			method: "GET", rawURL: "https://s3.eu-west-2.amazonaws.com/bucket/heliograph/status/lane1.txt",
		},
		{
			name: "put-log", why: "a write with a body, so the payload hash is not the empty-string one",
			method: "PUT", rawURL: "https://s3.eu-west-2.amazonaws.com/bucket/heliograph/logs/probe-20260912T134530Z.txt",
			body:   "10:00:00 | the measurement\n",
			header: map[string]string{"Content-Type": "text/plain"},
		},
		{
			name: "list-with-query", why: "a query string, which must be sorted and percent-encoded to the AWS rules rather than Go's",
			method: "GET", rawURL: "https://s3.eu-west-2.amazonaws.com/bucket?list-type=2&prefix=heliograph%2Flogs%2F&continuation-token=a%2Bb%3Dc",
		},
		{
			name: "path-needing-escapes", why: "a key with a space and a plus. AWS escapes a path differently from a query, and getting one rule for both is the classic signer bug",
			method: "GET", rawURL: "https://s3.eu-west-2.amazonaws.com/bucket/heliograph/logs/a%20b%2Bc.txt",
		},
		{
			name: "empty-body-put", why: "a zero-length body still hashes to the empty-string SHA-256, not to nothing",
			method: "PUT", rawURL: "https://s3.eu-west-2.amazonaws.com/bucket/heliograph/requests/lane1.txt",
			body: "",
		},
	}

	out := sigV4File{
		Note: "Golden SigV4 vectors from internal/transport/sigv4.go. Generated by " +
			"TestSigV4GoldenVectors -update-sigv4. The station's bash signer must reproduce " +
			"every field. A 403 from a real store names nothing, so these do.",
		AccessKey: c.accessKey, SecretKey: c.secretKey,
		Region: c.region, Service: c.service,
		Now: now.Format(isoLayout),
	}

	for _, s := range specs {
		u, err := url.Parse(s.rawURL)
		if err != nil {
			t.Fatalf("%s: %v", s.name, err)
		}
		req, err := http.NewRequest(s.method, u.String(), bytes.NewReader([]byte(s.body)))
		if err != nil {
			t.Fatalf("%s: %v", s.name, err)
		}
		for k, v := range s.header {
			req.Header.Set(k, v)
		}
		c.sign(req, []byte(s.body), now)

		// Rebuild the intermediates exactly as sign does. They are checked
		// against the header sign produced, so a drift here cannot pass.
		amzDate := now.Format(isoLayout)
		scopeDate := now.Format(dateLayout)
		payloadHash := sha256Hex([]byte(s.body))
		ch, sh := canonicalHeaders(req)
		canonical := strings.Join([]string{
			req.Method, canonicalURI(req.URL), canonicalQuery(req.URL), ch, sh, payloadHash,
		}, "\n")
		scope := strings.Join([]string{scopeDate, c.region, c.service, "aws4_request"}, "/")
		sts := strings.Join([]string{sigAlgorithm, amzDate, scope, sha256Hex([]byte(canonical))}, "\n")

		k1 := hmacSHA256([]byte("AWS4"+c.secretKey), scopeDate)
		k2 := hmacSHA256(k1, c.region)
		k3 := hmacSHA256(k2, c.service)
		k4 := hmacSHA256(k3, "aws4_request")
		sig := hex.EncodeToString(hmacSHA256(k4, sts))

		if got := req.Header.Get("Authorization"); !strings.HasSuffix(got, sig) {
			t.Fatalf("%s: the vector's own signature does not match the header sign produced:\n %s\n %s", s.name, got, sig)
		}

		hdr := map[string]string{}
		for k := range s.header {
			hdr[k] = s.header[k]
		}
		out.Cases = append(out.Cases, sigV4Case{
			Name: s.name, Why: s.why, Method: s.method, URL: s.rawURL, Body: s.body, Header: hdr,
			CanonicalRequest: canonical,
			CanonicalHash:    sha256Hex([]byte(canonical)),
			StringToSign:     sts,
			SigningKeyChain: []string{
				hex.EncodeToString(k1), hex.EncodeToString(k2),
				hex.EncodeToString(k3), hex.EncodeToString(k4),
			},
			Signature:     sig,
			Authorization: req.Header.Get("Authorization"),
			AmzDate:       amzDate,
			PayloadHash:   payloadHash,
		})
	}

	blob, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	blob = append(blob, '\n')

	if *updateSigV4 {
		if err := os.WriteFile(sigV4VectorPath, blob, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s (%d cases)", sigV4VectorPath, len(out.Cases))
		return
	}
	have, err := os.ReadFile(sigV4VectorPath)
	if err != nil {
		t.Fatalf("the committed SigV4 vectors are missing: %v\n"+
			"Run: go test ./internal/transport/ -run TestSigV4GoldenVectors -update-sigv4", err)
	}
	if !bytes.Equal(have, blob) {
		t.Errorf("the signer no longer produces the committed vectors.\n" +
			"Every station in the field signs the old way until it is re-planted, and " +
			"a wrong signature is a 403 that names nothing.\n" +
			"If the change is intended, regenerate:\n" +
			"  go test ./internal/transport/ -run TestSigV4GoldenVectors -update-sigv4")
	}
}

// The vectors are only worth having if this implementation is held to them too.
// Read back from the file, so the committed bytes are exercised rather than
// merely compared with themselves.
func TestTheCommittedSigV4VectorsStillSign(t *testing.T) {
	blob, err := os.ReadFile(sigV4VectorPath)
	if err != nil {
		t.Skipf("no committed vectors: %v", err)
	}
	var vf sigV4File
	if err := json.Unmarshal(blob, &vf); err != nil {
		t.Fatalf("the committed vectors are not readable: %v", err)
	}
	if len(vf.Cases) == 0 {
		t.Fatal("the vector file carries no cases, so this test asserted nothing")
	}
	now, err := time.Parse(isoLayout, vf.Now)
	if err != nil {
		t.Fatal(err)
	}
	c := creds{accessKey: vf.AccessKey, secretKey: vf.SecretKey, region: vf.Region, service: vf.Service}

	for _, tc := range vf.Cases {
		t.Run(tc.Name, func(t *testing.T) {
			req, err := http.NewRequest(tc.Method, tc.URL, bytes.NewReader([]byte(tc.Body)))
			if err != nil {
				t.Fatal(err)
			}
			for k, v := range tc.Header {
				req.Header.Set(k, v)
			}
			c.sign(req, []byte(tc.Body), now)
			if got := req.Header.Get("Authorization"); got != tc.Authorization {
				t.Errorf("Authorization differs\n got %s\nwant %s", got, tc.Authorization)
			}
		})
	}

	// AND THE KEY CHAIN IS REALLY HMAC-SHA256, checked here rather than taken
	// from the same code that wrote the file. A vector generated by a broken
	// derivation matches itself perfectly.
	k := []byte("AWS4" + vf.SecretKey)
	for i, part := range []string{
		time.Time(now).UTC().Format(dateLayout), vf.Region, vf.Service, "aws4_request",
	} {
		m := hmac.New(sha256.New, k)
		m.Write([]byte(part))
		k = m.Sum(nil)
		if got := hex.EncodeToString(k); got != vf.Cases[0].SigningKeyChain[i] {
			t.Errorf("signing key stage %d differs\n got %s\nwant %s", i+1, got, vf.Cases[0].SigningKeyChain[i])
		}
	}
}
